# Site settings
title: Blog For Better
email: visunal@163.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leraybetter.com" # the base hostname & protocol for your site
twitter_username: lanusiv
github_username:  lanusiv

# Build settings
markdown: kramdown
#excerpt_separator: <...>
paginate: 10

#custom collections
collections:
- albums

collections:
 albums:
   foo: bar
   output: true

defaults:
  - scope:
      path: ""
      type: albums
    values:
      layout: page

